---
# install docker community edition. See:
# https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

- name: "install necessary packages"
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: "add GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: "get version name"
  shell: lsb_release -cs
  register: lsb_release

- name: "add repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

- name: "install docker"
  apt:
    name: docker-ce
    update_cache: yes

# install nvidia-docker
- name: "get nvidia-docker deb"
  get_url:
    url: "{{ nvidia_docker.prefix }}/{{ nvidia_docker.pkg_name }}"
    dest: "{{ setup_dir }}"

- name: "install nvidia-docker"
  apt:
    deb: "{{ setup_dir }}/{{ nvidia_docker.pkg_name }}"