---
- name: "make setup directory"
  file:
    path: "{{ setup_dir }}"
    state: directory

# install CUDA on Ubuntu 16.04. See:
# https://developer.nvidia.com/cuda-downloads

- name: "get cuda toolkit package"
  get_url:
    url: "{{ cuda.prefix }}/{{ cuda.pkg_name }}"
    dest: "{{ setup_dir }}"

- name: "unpack cuda toolkit package"
  apt:
    deb: "{{ setup_dir }}/{{ cuda.pkg_name }}"

- name: "install cuda"
  apt:
    name: cuda
    update_cache: yes