---
- name: "make setup directory"
  file:
    path: /home/ubuntu/setup
    state: directory

# install CUDA on Ubuntu 16.04. See:
# https://developer.nvidia.com/cuda-downloads

- name: "get cuda toolkit package"
  get_url:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
    dest: /home/ubuntu/setup

- name: "unpack cuda toolkit package"
  apt:
    deb: /home/ubuntu/setup/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb

- name: "install cuda"
  apt:
    name: cuda
    update_cache: yes